### ISSUE TITLE
Scan as if scanning twice at the same time --> 2 labels printed with label 2 tmp 

### ISSUE THREAD

**Issue by HeloiseCoen** [digital-botanical-gardens-initiative/DBGI_tracking_android#6]
When scanning a new sample, scan as if scanning twice. 2 labels printed at the same time with label 2 tmp

**Comment by edouardbruelhart** [comment]
I tried to reproduce the bug and effectively, when the submit button is pressed 2 times in a short interval, 2 labels are generated in the db and 2 labels of the second added are printed. I will correct this bug as soon as possible

**Comment by edouardbruelhart** [comment]
It should now be impossible to reproduce this bug. The button is hidden and unclickable after first click, until a new sample is scanned.
